AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - db/migrate/*
    - vendor/**/*
    - config/deploy.rb
    - config/unicorn.rb
  # Rails向けのRails copsを実行。"rubocop -R"と同じ
  Rails:
    enabled: true

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
Style/StringLiterals:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false

#'frozen_string_literal: true'を無効
Style/FrozenStringLiteralComment:
  Enabled: false

# Use only ascii symbols in comments.を無視
Style/AsciiComments:
  Enabled: false

# Block has too many lines.を無視
Metrics/BlockLength:
  Enabled: false

# Class has too many lines.を無視
Metrics/ClassLength:
  Enabled: false

# Method has too many lines
Metrics/MethodLength:
  Enabled: false

# Use nested module/class definitions instead of compact style.
Style/ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false
